name: CI/CD Node.js & Docker

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build & Test Node.js
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Exécuter les tests
      - name: Run tests
        run: npm test

      # 5. Vérifier le code avec lint
      - name: Lint code
        run: npm run lint || echo "Lint warnings"

  docker:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Login Docker (Docker Hub)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build l'image Docker
      - name: Build Docker image
        run: docker build -t elena94s/examen-nodejs:latest .

      # Push l'image Docker
      - name: Push Docker image
        run: docker push elena94s/examen-nodejs:latest
        if: github.ref == 'refs/heads/main'
